### ISSUE TITLE
"hugo new" seems not to work with this theme

### ISSUE THREAD

**Issue by r4dh4l** [VVelox/hugo-dusky-neon-potato#1]
Hi,

thank you for this beautiful hugo theme. Unfortunately I wasn't able to add content via `hugo new test/test.md` - is the theme still working with hugo v0.51?

**Comment by fu-sen** [comment]
Have you kept watching the pure white screen with **"hugo server"**? Probably this is involved:
https://github.com/VVelox/hugo-dusky-neon-potato/issues/2

**Comment by r4dh4l** [comment]
Well, I couldn't remember if I stumbled over https://github.com/VVelox/hugo-dusky-neon-potato/issues/2 as well but I just confirmed that https://github.com/VVelox/hugo-dusky-neon-potato/issues/2 is not my problem: I get a default page with the expected theme but there is no content added via `hugo new test/my-first-post.md`.

**Comment by VVelox** [comment]
Howdy!

I can safely say it is working with v0.55.4.

What sort of errors is it throwing?
 
Did you make sure to run hugo to regen the directory tree it all is being published to?

**Comment by VVelox** [comment]
BTW very sorry about the slow reply.

**Comment by r4dh4l** [comment]
@VVelox thx for your reply. Unfortunately I already switched to another theme and don't have time to test yours atm. Will report asap.
