### ISSUE TITLE
README.md and real (GitHub project) theme name are different.

### ISSUE THREAD

**Issue by fu-sen** [VVelox/hugo-dusky-neon-potato#2]
[**README.md**](https://github.com/VVelox/hugo-dusky-neon-potato/blob/master/README.md) has the following description:
___

## Usage

Use hugo's -t dusky-neon-potato or --theme=dusky-neon-potato option with hugo commands. Example:

```shell
$ hugo server -t dusky-neon-potato -w -D
```

___

but this (GitHub project) name is **hugo-dusky-neon-potato**. This will not work. You need to fix it.

Why is not this in [config.toml](https://github.com/VVelox/hugo-dusky-neon-potato/blob/master/exampleSite/config.toml) better than that?:

```
theme = "hugo-dusky-neon-potato"
```

**Comment by VVelox** [comment]
Awesome! Fixed in both areas. :)
